"""Exact n=8 LFO census by extending the exact n=7 census.

Every n-vertex tournament has an (n-1)-vertex induced subtournament.
Therefore all non-isomorphic n-vertex tournaments can be generated by
adding one vertex in all possible ways to the non-isomorphic
(n-1)-vertex tournaments and then deduplicating up to isomorphism.

For n=8 this is small:

    456 exact n=7 representatives * 2^7 extensions = 58,368 candidates,
    deduplicating to 6,880 non-isomorphic n=8 tournaments.

The LFO decision is done by `lfo_backtrack.find_lfo_order`, and the size
bound is classified by a standard O(n 2^n) dynamic program for the
minimum feedback arc set size of a tournament.
"""
from __future__ import annotations

import argparse
import itertools
import json
import os
import sys
import time
from collections import Counter
from typing import Iterable, Sequence

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from lfo_backtrack import find_lfo_order  # noqa: E402
from lfo_forbidden7_test import contained_no7_kind, load_no7_keys  # noqa: E402
from lfo_score_bucket import canonical_key_with_scores, score_sequence  # noqa: E402


def extend_by_one(T: Sequence[Sequence[int]]) -> Iterable[list[list[int]]]:
    n = len(T)
    for bits in itertools.product((0, 1), repeat=n):
        U = [list(row) + [0] for row in T]
        U.append([0] * (n + 1))
        for i, b in enumerate(bits):
            if b:
                U[n][i] = 1
            else:
                U[i][n] = 1
        yield U


def load_base_representatives(path: str) -> list[list[list[int]]]:
    with open(path) as f:
        data = json.load(f)
    return [r["T"] for b in data["buckets"] for r in b["records"]]


def min_fas_dp(T: Sequence[Sequence[int]]) -> int:
    """Return the minimum number of back-arcs over all vertex orders."""
    n = len(T)
    inf = n * n
    dp = [inf] * (1 << n)
    dp[0] = 0
    for mask in range(1, 1 << n):
        best = inf
        mm = mask
        while mm:
            bit = mm & -mm
            x = bit.bit_length() - 1
            rest = mask ^ bit
            cost = 0
            rr = rest
            while rr:
                ybit = rr & -rr
                y = ybit.bit_length() - 1
                if T[x][y]:
                    cost += 1
                rr ^= ybit
            cand = dp[rest] + cost
            if cand < best:
                best = cand
            mm ^= bit
        dp[mask] = best
    return dp[(1 << n) - 1]


def main() -> None:
    here = os.path.dirname(os.path.abspath(__file__))
    default_base = os.path.join(here, "..", "data", "lfo_full_n7.json")
    default_out = os.path.join(here, "..", "data", "lfo_extend_census_n8.json")

    p = argparse.ArgumentParser()
    p.add_argument("--base", default=default_base)
    p.add_argument("--forbidden7", default=default_base)
    p.add_argument("--out", default=default_out)
    p.add_argument("--progress", type=int, default=500)
    args = p.parse_args()

    t0 = time.time()
    base = load_base_representatives(args.base)
    reps: dict[tuple[int, ...], list[list[int]]] = {}
    for T in base:
        for U in extend_by_one(T):
            reps.setdefault(canonical_key_with_scores(U), U)

    all_no7, size_no7, combinatorial_no7 = load_no7_keys(args.forbidden7)

    no_records = []
    summary_counter: Counter[str] = Counter()
    score_no_hist: Counter[str] = Counter()
    score_yes_hist: Counter[str] = Counter()
    search_nodes = 0

    for idx, T in enumerate(reps.values()):
        out = find_lfo_order(T)
        search_nodes += out["nodes"]
        seq = score_sequence(T)
        if out["found"]:
            summary_counter["lfo_yes"] += 1
            score_yes_hist[str(seq)] += 1
        else:
            summary_counter["lfo_no"] += 1
            score_no_hist[str(seq)] += 1
            min_fas = min_fas_dp(T)
            no_kind = "size" if min_fas > len(T) - 1 else "combinatorial"
            summary_counter[f"{no_kind}_no"] += 1
            hit = contained_no7_kind(T, all_no7, size_no7, combinatorial_no7)
            summary_counter[
                "no_contains_order7_no" if hit["contains_no7"] else "no_order7_free"
            ] += 1
            no_records.append({
                "iso_index": idx,
                "score_sequence": list(seq),
                "min_fas": min_fas,
                "no_kind": no_kind,
                "contains_order7_no": hit["contains_no7"],
                "order7_hit_count": hit["hit_count"],
                "order7_hit_kind_hist": hit["hit_kind_hist"],
                "T": T,
                "search": out,
            })

        if args.progress and (idx + 1) % args.progress == 0:
            print(f"classified {idx + 1}/{len(reps)}; "
                  f"YES={summary_counter['lfo_yes']} NO={summary_counter['lfo_no']}",
                  flush=True)

    summary = {
        "base": os.path.relpath(args.base, os.path.join(here, "..")),
        "n": 8,
        "base_representatives": len(base),
        "extensions": len(base) * (2 ** 7),
        "non_iso_total": len(reps),
        "seconds": round(time.time() - t0, 2),
        "avg_search_nodes": round(search_nodes / len(reps), 2),
        **dict(sorted(summary_counter.items())),
        "score_no_hist": dict(sorted(score_no_hist.items())),
        "score_yes_hist": dict(sorted(score_yes_hist.items())),
    }
    data = {"summary": summary, "no_records": no_records}
    os.makedirs(os.path.dirname(os.path.abspath(args.out)), exist_ok=True)
    with open(args.out, "w") as f:
        json.dump(data, f, indent=2)
    print(json.dumps(summary, indent=2))
    print(f"wrote {args.out}")


if __name__ == "__main__":
    main()
