"""Route-B OLS empirical sweep (companion to `team/15_v6_ols_empirical.md`).

This driver mirrors `run_phase4_vehicle6.py` but operates on OLS digraphs
generated by `code/generators/ols.py`. For each candidate we:

  1. confirm OLS via the independent predicate
     `is_out_locally_semicomplete(D)`;
  2. confirm arc-connectivity is exactly 3 (the target regime);
  3. cross-check ILP + SAT, expect SAT (Route B theorem);
  4. log the SAT witness;
  5. test CL1's two hypotheses on the witness:
        (1) D[V_1] and D[V_2] admit a SAD (we restrict the witness to
            each part and check strong connectivity of each colour);
        (2) bridges from V_1 to V_2 and V_2 to V_1 admit a 2-coloring
            with each (direction, colour) class non-empty (just count
            bridges per colour per direction in the witness);
  6. compute the canonical hash.

Hard rules enforced:
  - witness logging mandatory for every SAT instance;
  - hit-rate floor (>= 5 % at lambda = 3 gate);
  - independent OLS verification (Construction A's construction does
    not bypass `is_out_locally_semicomplete`);
  - stop-on-lambda=3 UNSAT (write a counterexample notice).

Outputs:
  - JSON log at code/logs/route_b_ols_<timestamp>.json with full
    witnesses, canonical hashes, per-instance CL1 records.
"""

from __future__ import annotations

import argparse
import json
import sys
import time
from collections import Counter, defaultdict
from dataclasses import asdict, dataclass, field
from pathlib import Path
from typing import Any

HERE = Path(__file__).resolve().parent
if str(HERE) not in sys.path:
    sys.path.insert(0, str(HERE))

from cross_check import cross_check  # noqa: E402
from digraph import Digraph  # noqa: E402
from generators.canonicalize import canonical_key  # noqa: E402
from generators.ols import (  # noqa: E402
    OlsInstance,
    SEMICOMPLETE_SHAPES,
    enumerate_construction_A,
    enumerate_construction_B,
    enumerate_construction_C,
    is_out_locally_semicomplete,
    is_semicomplete,
)
from verifier_sat import verify_sat  # noqa: E402


# ----------------------------------------------------------------------------
# Per-instance CL1 record
# ----------------------------------------------------------------------------


@dataclass
class CL1Record:
    """Per-instance CL1 hypothesis-test record.

    Hypothesis (1) is the intrinsic SAD-decomposability of each part
    D[V_1] and D[V_2]. We test it by running `verify_sat` on each
    induced subdigraph (treating it as a stand-alone digraph). A part
    of size 1 is vacuously "SAD-decomposable" (it has no arcs to
    decompose).

    Hypothesis (2) is the bridge 2-coloring with each (direction,
    colour) class non-empty. We read it off the original witness on D
    directly.
    """

    # Partition V = V_1 \cup V_2 chosen (V_1 = anchor component for A;
    # for B/C the partition is heuristic — first half / second half by
    # vertex index).
    v1_size: int = 0
    v2_size: int = 0
    v1: list[int] = field(default_factory=list)
    v2: list[int] = field(default_factory=list)

    # Hypothesis (1): intrinsic SAD-decomposability of D[V_i].
    v1_lambda: int = 0
    v2_lambda: int = 0
    v1_sad_status: str = "?"  # SAT, UNSAT, UNKNOWN, NA (trivial part)
    v2_sad_status: str = "?"

    # Number of arcs of each colour on each inner part (as a *witness*
    # restriction sanity check; if the witness restricts to a SAD, it
    # would be the cleanest proof).
    inner1_red_n_arcs: int = 0
    inner1_blue_n_arcs: int = 0
    inner2_red_n_arcs: int = 0
    inner2_blue_n_arcs: int = 0
    inner1_red_strong: bool = False
    inner1_blue_strong: bool = False
    inner2_red_strong: bool = False
    inner2_blue_strong: bool = False

    # Hypothesis (2): bridge 2-coloring with each (direction, colour)
    # non-empty.
    bridges_plus_total: int = 0  # V_1 -> V_2
    bridges_minus_total: int = 0  # V_2 -> V_1
    bridges_plus_R: int = 0
    bridges_plus_B: int = 0
    bridges_minus_R: int = 0
    bridges_minus_B: int = 0

    @property
    def hypothesis_1_holds(self) -> bool:
        """Both parts admit a SAD (intrinsic test)."""
        ok = []
        for st in (self.v1_sad_status, self.v2_sad_status):
            if st in ("SAT", "NA"):
                ok.append(True)
            else:
                ok.append(False)
        return all(ok)

    @property
    def hypothesis_2_holds(self) -> bool:
        """Each (direction, colour) class is non-empty."""
        return (
            self.bridges_plus_R > 0 and self.bridges_plus_B > 0
            and self.bridges_minus_R > 0 and self.bridges_minus_B > 0
        )


def _keyed_arcs(arcs: list[tuple[int, int]]) -> list[tuple[int, int, int]]:
    ctr: Counter = Counter()
    out: list[tuple[int, int, int]] = []
    for (u, v) in arcs:
        k = ctr[(u, v)]
        out.append((u, v, k))
        ctr[(u, v)] += 1
    return out


def _choose_partition(inst: OlsInstance) -> tuple[list[int], list[int]]:
    """Choose CL1 partition V = V_1 \cup V_2.

    Construction A: V_1 = first component C_1; V_2 = V \ V_1.
    Constructions B, C: heuristic — V_1 = first half of vertices by
    index, V_2 = second half (both sizes >= 2).
    """
    if inst.construction == "A_round" and inst.components:
        v1 = sorted(inst.components[0])
        v2 = sorted(v for v in range(inst.n) if v not in set(v1))
        return v1, v2
    half = inst.n // 2
    v1 = list(range(half))
    v2 = list(range(half, inst.n))
    return v1, v2


def _induced_subdigraph(D: Digraph, vertex_set: list[int]) -> Digraph:
    """Build the induced subdigraph D[vertex_set] preserving parallel arcs."""
    S = set(vertex_set)
    arcs = []
    for u, v, _k in D.arcs():
        if u in S and v in S:
            arcs.append((u, v))
    return Digraph.from_arcs(sorted(S), arcs)


def analyse_cl1(
    inst: OlsInstance,
    D: Digraph,
    witness: tuple[list[tuple[int, int, int]], list[tuple[int, int, int]]],
    instance_time_s: float = 8.0,
) -> CL1Record:
    red_arcs, blue_arcs = witness
    red_set = set(red_arcs)
    v1_list, v2_list = _choose_partition(inst)
    v1_set = set(v1_list)
    v2_set = set(v2_list)
    rec = CL1Record(
        v1_size=len(v1_list),
        v2_size=len(v2_list),
        v1=list(v1_list),
        v2=list(v2_list),
    )

    # Restrict witness arcs to inner V_1 and V_2; count bridges.
    inner1_red: list[tuple[int, int, int]] = []
    inner1_blue: list[tuple[int, int, int]] = []
    inner2_red: list[tuple[int, int, int]] = []
    inner2_blue: list[tuple[int, int, int]] = []
    for ke in red_arcs + blue_arcs:
        u, v, _k = ke
        u_in_1 = u in v1_set
        v_in_1 = v in v1_set
        is_red = ke in red_set
        if u_in_1 and v_in_1:
            if is_red:
                inner1_red.append(ke)
            else:
                inner1_blue.append(ke)
        elif (not u_in_1) and (not v_in_1):
            if is_red:
                inner2_red.append(ke)
            else:
                inner2_blue.append(ke)
        elif u_in_1 and not v_in_1:
            rec.bridges_plus_total += 1
            if is_red:
                rec.bridges_plus_R += 1
            else:
                rec.bridges_plus_B += 1
        else:
            rec.bridges_minus_total += 1
            if is_red:
                rec.bridges_minus_R += 1
            else:
                rec.bridges_minus_B += 1

    rec.inner1_red_n_arcs = len(inner1_red)
    rec.inner1_blue_n_arcs = len(inner1_blue)
    rec.inner2_red_n_arcs = len(inner2_red)
    rec.inner2_blue_n_arcs = len(inner2_blue)

    # Strong-connectivity of restricted colour classes on each part.
    if v1_list:
        R1 = Digraph.from_arcs(v1_list, [(u, v) for (u, v, _k) in inner1_red])
        B1 = Digraph.from_arcs(v1_list, [(u, v) for (u, v, _k) in inner1_blue])
        rec.inner1_red_strong = R1.is_strongly_connected() if len(v1_list) >= 2 else True
        rec.inner1_blue_strong = B1.is_strongly_connected() if len(v1_list) >= 2 else True
    if v2_list:
        R2 = Digraph.from_arcs(v2_list, [(u, v) for (u, v, _k) in inner2_red])
        B2 = Digraph.from_arcs(v2_list, [(u, v) for (u, v, _k) in inner2_blue])
        rec.inner2_red_strong = R2.is_strongly_connected() if len(v2_list) >= 2 else True
        rec.inner2_blue_strong = B2.is_strongly_connected() if len(v2_list) >= 2 else True

    # Hypothesis (1), intrinsic: run verify_sat on D[V_1] and D[V_2].
    # Trivial parts (n <= 1) are SAD by convention.
    for vlist, status_attr, lam_attr in (
        (v1_list, "v1_sad_status", "v1_lambda"),
        (v2_list, "v2_sad_status", "v2_lambda"),
    ):
        if len(vlist) <= 1:
            setattr(rec, status_attr, "NA")
            setattr(rec, lam_attr, 0)
            continue
        Dpart = _induced_subdigraph(D, vlist)
        if not Dpart.is_strongly_connected():
            setattr(rec, status_attr, "UNSAT")  # not strong => no SAD
            setattr(rec, lam_attr, 0)
            continue
        lam = Dpart.arc_connectivity()
        setattr(rec, lam_attr, lam)
        if lam < 2:
            # 1-arc-strong digraphs cannot have a SAD: each colour class
            # would need to be strong, requiring lambda >= 2 in the
            # original. Mark UNSAT without running the solver.
            setattr(rec, status_attr, "UNSAT")
            continue
        res = verify_sat(Dpart, time_limit_s=instance_time_s)
        setattr(rec, status_attr, res.get("status", "UNKNOWN"))

    return rec


# ----------------------------------------------------------------------------
# Sweep dataclasses
# ----------------------------------------------------------------------------


@dataclass
class OlsStats:
    streamed: int = 0
    ols_confirmed: int = 0
    strong: int = 0
    kappa3_pass: int = 0
    kappa_higher: int = 0
    kappa_lower: int = 0
    verified_sat: int = 0
    verified_unsat: int = 0
    disagreements: int = 0
    elapsed_s: float = 0.0

    by_construction: dict[str, int] = field(default_factory=dict)
    by_construction_k3: dict[str, int] = field(default_factory=dict)
    by_construction_sat: dict[str, int] = field(default_factory=dict)


@dataclass
class OlsLog:
    started_at: str
    config: dict[str, Any] = field(default_factory=dict)
    stats: dict[str, Any] = field(default_factory=dict)
    candidates: list[dict[str, Any]] = field(default_factory=list)
    canonical_summary: dict[str, Any] = field(default_factory=dict)
    cl1_summary: dict[str, Any] = field(default_factory=dict)
    counterexamples: list[dict[str, Any]] = field(default_factory=list)
    finished_at: str | None = None
    elapsed_s: float | None = None
    notes: list[str] = field(default_factory=list)


# ----------------------------------------------------------------------------
# Driver
# ----------------------------------------------------------------------------


def _instance_to_entry(
    inst: OlsInstance,
    witness: tuple[list[tuple[int, int, int]], list[tuple[int, int, int]]],
    cross: Any,
    cl1: CL1Record,
    canonical: str,
) -> dict[str, Any]:
    red, blue = witness
    return {
        "name": inst.name,
        "n": inst.n,
        "m": len(inst.arcs),
        "construction": inst.construction,
        "components": [list(c) for c in inst.components],
        "component_shapes": list(inst.component_shapes),
        "arcs": [list(a) for a in inst.arcs],
        "ilp_status": cross.ilp.get("status"),
        "sat_status": cross.sat.get("status"),
        "ilp_time": cross.ilp.get("time_s"),
        "sat_time": cross.sat.get("time_s"),
        "witness_red": [[u, v, k] for (u, v, k) in red],
        "witness_blue": [[u, v, k] for (u, v, k) in blue],
        "canonical_hash": canonical,
        "cl1": asdict(cl1),
    }


def _unsat_entry(inst: OlsInstance, cross: Any) -> dict[str, Any]:
    return {
        "name": inst.name,
        "n": inst.n,
        "m": len(inst.arcs),
        "construction": inst.construction,
        "components": [list(c) for c in inst.components],
        "component_shapes": list(inst.component_shapes),
        "arcs": [list(a) for a in inst.arcs],
        "ilp_status": cross.ilp.get("status"),
        "sat_status": cross.sat.get("status"),
    }


def stream_candidates(
    cap_A: int,
    cap_B: int,
    cap_C: int,
    seed: int,
) -> list[OlsInstance]:
    """Build a deterministic shuffled stream from A, B, C generators."""
    out: list[OlsInstance] = []
    seen_arcs: set[tuple[tuple[int, int], ...]] = set()
    for inst in enumerate_construction_A(seed=seed, cap_per_p=cap_A // 4 + 5):
        key = tuple(sorted(inst.arcs))
        if key in seen_arcs:
            continue
        seen_arcs.add(key)
        out.append(inst)
        if sum(1 for x in out if x.construction == "A_round") >= cap_A:
            break
    nB = 0
    for inst in enumerate_construction_B(seed=seed + 1, cap=cap_B):
        key = tuple(sorted(inst.arcs))
        if key in seen_arcs:
            continue
        seen_arcs.add(key)
        out.append(inst)
        nB += 1
        if nB >= cap_B:
            break
    nC = 0
    for inst in enumerate_construction_C(seed=seed + 2, cap_attempts=cap_C * 80):
        key = tuple(sorted(inst.arcs))
        if key in seen_arcs:
            continue
        seen_arcs.add(key)
        out.append(inst)
        nC += 1
        if nC >= cap_C:
            break
    # Don't shuffle: process A first (most structured), then B, then C.
    return out


def run_sweep(
    candidates: list[OlsInstance],
    instance_time_s: float,
    log: OlsLog,
) -> None:
    stats = OlsStats()
    t0 = time.time()
    by_constr: dict[str, int] = defaultdict(int)
    by_constr_k3: dict[str, int] = defaultdict(int)
    by_constr_sat: dict[str, int] = defaultdict(int)

    for inst in candidates:
        stats.streamed += 1
        by_constr[inst.construction] += 1

        # 1. Independent OLS check.
        D = inst.build()
        if not is_out_locally_semicomplete(D):
            # The generator should never produce non-OLS for A_round / B_tail.
            log.notes.append(
                f"NON-OLS generated (BUG?): {inst.name}"
            )
            continue
        stats.ols_confirmed += 1

        # 2. Strongly connected?
        if not D.is_strongly_connected():
            continue
        stats.strong += 1

        # 3. Arc connectivity gate: exactly 3.
        lam = D.arc_connectivity()
        if lam < 3:
            stats.kappa_lower += 1
            continue
        if lam > 3:
            stats.kappa_higher += 1
            continue
        stats.kappa3_pass += 1
        by_constr_k3[inst.construction] += 1

        # 4. Cross-check ILP + SAT.
        cross = cross_check(D, inst.name, time_limit_s=instance_time_s)
        if not cross.agree:
            stats.disagreements += 1
            log.notes.append(
                f"FATAL: cross-check disagree on {inst.name}: "
                f"ILP={cross.ilp.get('status')} SAT={cross.sat.get('status')}"
            )
            print(f"  *** FATAL DISAGREE: {inst.name}", flush=True)
            continue

        status = cross.ilp.get("status")
        if status == "UNSAT":
            stats.verified_unsat += 1
            print(
                f"  *** UNSAT 3-arc-strong OLS candidate ***  name={inst.name}  "
                f"n={inst.n}  m={len(inst.arcs)}  construction={inst.construction}",
                flush=True,
            )
            log.notes.append(
                f"COUNTEREXAMPLE candidate (Route B): {inst.name} -- "
                f"run team/01 checklist; write team/12_candidate_counterexample.md"
            )
            log.counterexamples.append(_unsat_entry(inst, cross))
            # Per spec hard rule: stop on lambda=3 UNSAT.
            print(
                "  *** STOPPING SWEEP: lambda=3 OLS UNSAT triggers "
                "team/01 ten-item checklist. ***",
                flush=True,
            )
            break

        if status != "SAT":
            log.notes.append(
                f"UNKNOWN status on {inst.name}: ILP={status} "
                f"SAT={cross.sat.get('status')}"
            )
            continue

        stats.verified_sat += 1
        by_constr_sat[inst.construction] += 1
        witness = cross.sat.get("witness")
        if witness is None:
            log.notes.append(f"no SAT witness recovered for {inst.name}")
            continue

        cl1 = analyse_cl1(inst, D, witness, instance_time_s=instance_time_s)
        canonical = canonical_key(D)
        entry = _instance_to_entry(inst, witness, cross, cl1, canonical)
        log.candidates.append(entry)

        if stats.streamed % 50 == 0:
            print(
                f"  [OLS] streamed={stats.streamed} ols={stats.ols_confirmed} "
                f"k3={stats.kappa3_pass} sat={stats.verified_sat} "
                f"unsat={stats.verified_unsat} elapsed={time.time() - t0:.0f}s",
                flush=True,
            )

    stats.elapsed_s = time.time() - t0
    stats.by_construction = dict(by_constr)
    stats.by_construction_k3 = dict(by_constr_k3)
    stats.by_construction_sat = dict(by_constr_sat)
    log.stats = asdict(stats)


# ----------------------------------------------------------------------------
# Aggregation
# ----------------------------------------------------------------------------


def _h1_passes(cl1: dict[str, Any]) -> bool:
    """Hypothesis (1) is satisfied iff both parts have status SAT or NA."""
    return (
        cl1.get("v1_sad_status") in ("SAT", "NA")
        and cl1.get("v2_sad_status") in ("SAT", "NA")
    )


def _h2_passes(cl1: dict[str, Any]) -> bool:
    return (
        cl1.get("bridges_plus_R", 0) > 0
        and cl1.get("bridges_plus_B", 0) > 0
        and cl1.get("bridges_minus_R", 0) > 0
        and cl1.get("bridges_minus_B", 0) > 0
    )


def aggregate_cl1(log: OlsLog) -> dict[str, Any]:
    cands = [c for c in log.candidates if c.get("sat_status") == "SAT"]
    if not cands:
        return {"n_candidates": 0}

    n = len(cands)
    h1_pass = sum(1 for c in cands if _h1_passes(c["cl1"]))
    h2_pass = sum(1 for c in cands if _h2_passes(c["cl1"]))
    both_pass = sum(
        1 for c in cands if _h1_passes(c["cl1"]) and _h2_passes(c["cl1"])
    )

    # Per-construction breakdown.
    per_constr: dict[str, dict[str, Any]] = {}
    bk: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for c in cands:
        bk[c["construction"]].append(c)
    for k, b in bk.items():
        m = len(b)
        h1 = sum(1 for c in b if _h1_passes(c["cl1"]))
        h2 = sum(1 for c in b if _h2_passes(c["cl1"]))
        per_constr[k] = {
            "n": m,
            "h1_pass": h1,
            "h1_frac": h1 / m,
            "h2_pass": h2,
            "h2_frac": h2 / m,
        }

    # Per-component-shape breakdown for Construction A (the meaningful
    # Route B regime). The anchor is the *first* component, which is
    # what _choose_partition uses as V_1.
    per_anchor: dict[str, dict[str, Any]] = {}
    bk_anchor: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for c in cands:
        if c["construction"] != "A_round":
            continue
        if not c["component_shapes"]:
            continue
        anchor = c["component_shapes"][0]
        bk_anchor[anchor].append(c)
    for k, b in bk_anchor.items():
        m = len(b)
        h1 = sum(1 for c in b if _h1_passes(c["cl1"]))
        h2 = sum(1 for c in b if _h2_passes(c["cl1"]))
        per_anchor[k] = {
            "n": m,
            "h1_pass": h1,
            "h1_frac": h1 / m,
            "h2_pass": h2,
            "h2_frac": h2 / m,
        }

    # H1-failure breakdown: which part fails, and why? Useful for the
    # diagnostic exception-family discussion.
    h1_fail_details: dict[str, int] = defaultdict(int)
    for c in cands:
        if _h1_passes(c["cl1"]):
            continue
        v1s = c["cl1"]["v1_sad_status"]
        v2s = c["cl1"]["v2_sad_status"]
        h1_fail_details[f"V1={v1s}, V2={v2s}"] += 1

    return {
        "n_candidates": n,
        "hypothesis_1_pass": h1_pass,
        "hypothesis_1_frac": h1_pass / n,
        "hypothesis_2_pass": h2_pass,
        "hypothesis_2_frac": h2_pass / n,
        "both_pass": both_pass,
        "both_frac": both_pass / n,
        "per_construction": per_constr,
        "per_anchor_shape_A": per_anchor,
        "h1_failure_breakdown": dict(h1_fail_details),
    }


def aggregate_canonical(log: OlsLog) -> dict[str, Any]:
    cands = [c for c in log.candidates if c.get("sat_status") == "SAT"]
    keys: dict[str, list[str]] = defaultdict(list)
    for c in cands:
        keys[c["canonical_hash"]].append(c["name"])
    classes = sorted(keys.values(), key=len, reverse=True)
    size_dist = Counter(len(c) for c in classes)
    return {
        "n_labeled_distinct": len(cands),
        "n_canonical_distinct": len(keys),
        "largest_iso_class_size": len(classes[0]) if classes else 0,
        "iso_class_size_distribution": {
            str(k): v for k, v in sorted(size_dist.items())
        },
    }


# ----------------------------------------------------------------------------
# Main
# ----------------------------------------------------------------------------


def main() -> int:
    p = argparse.ArgumentParser(description="Route-B OLS empirical sweep")
    p.add_argument("--cap-A", type=int, default=600, help="cap on Construction A")
    p.add_argument("--cap-B", type=int, default=40, help="cap on Construction B")
    p.add_argument("--cap-C", type=int, default=120, help="cap on Construction C")
    p.add_argument("--instance-time-s", type=float, default=10.0)
    p.add_argument("--logs-dir", default=str(HERE / "logs"))
    p.add_argument("--seed", type=int, default=20260516)
    args = p.parse_args()

    timestamp = time.strftime("%Y%m%d_%H%M%S")
    logs_dir = Path(args.logs_dir)
    logs_dir.mkdir(parents=True, exist_ok=True)
    log_path = logs_dir / f"route_b_ols_{timestamp}.json"

    print("=" * 72, flush=True)
    print("Route B — 3-arc-strong OLS empirical sweep", flush=True)
    print("=" * 72, flush=True)

    print(f"Semicomplete shape catalog: {len(SEMICOMPLETE_SHAPES)} entries", flush=True)
    for sh in SEMICOMPLETE_SHAPES:
        print(f"  shape={sh.name:6s} n={sh.n}", flush=True)
    print(flush=True)

    log = OlsLog(
        started_at=time.strftime("%Y-%m-%d %H:%M:%S"),
        config={
            "cap_A": args.cap_A,
            "cap_B": args.cap_B,
            "cap_C": args.cap_C,
            "instance_time_s": args.instance_time_s,
            "seed": args.seed,
        },
    )

    candidates = stream_candidates(args.cap_A, args.cap_B, args.cap_C, args.seed)
    print(f"Streamed candidate list: {len(candidates)} instances", flush=True)
    constr_count = Counter(c.construction for c in candidates)
    for k, v in constr_count.items():
        print(f"  {k}: {v}", flush=True)
    print(flush=True)

    t0 = time.time()
    run_sweep(
        candidates=candidates,
        instance_time_s=args.instance_time_s,
        log=log,
    )

    log.cl1_summary = aggregate_cl1(log)
    log.canonical_summary = aggregate_canonical(log)
    log.finished_at = time.strftime("%Y-%m-%d %H:%M:%S")
    log.elapsed_s = time.time() - t0

    # ---- stdout report -----------------------------------------------------
    print("=" * 72, flush=True)
    print("Sweep complete.", flush=True)
    s = log.stats
    print(
        f"  streamed={s['streamed']} ols={s['ols_confirmed']} strong={s['strong']} "
        f"kappa=3 exactly={s['kappa3_pass']} kappa>3 (rej)={s['kappa_higher']} "
        f"kappa<3={s['kappa_lower']}",
        flush=True,
    )
    print(
        f"  verified_sat={s['verified_sat']} verified_unsat={s['verified_unsat']} "
        f"disagreements={s['disagreements']} elapsed={s['elapsed_s']:.0f}s",
        flush=True,
    )
    hit_rate = s["kappa3_pass"] / max(s["streamed"], 1)
    print(
        f"  hit-rate(lambda=3 | streamed) = {100 * hit_rate:.1f}% "
        f"(floor 5%; {'OK' if hit_rate >= 0.05 else 'BELOW FLOOR'})",
        flush=True,
    )

    cs = log.canonical_summary
    print(
        f"  canonical: {cs['n_labeled_distinct']} labeled-distinct -> "
        f"{cs['n_canonical_distinct']} canonical-distinct  "
        f"(largest iso-class={cs['largest_iso_class_size']})",
        flush=True,
    )

    print(f"\nBy construction:", flush=True)
    bc = s.get("by_construction", {})
    bk = s.get("by_construction_k3", {})
    bs = s.get("by_construction_sat", {})
    for k in sorted(bc.keys()):
        print(
            f"  {k:12s} streamed={bc.get(k, 0):4d}  "
            f"lambda3={bk.get(k, 0):4d}  sat={bs.get(k, 0):4d}",
            flush=True,
        )

    cl1s = log.cl1_summary
    if cl1s.get("n_candidates", 0) > 0:
        print("\n" + "=" * 72, flush=True)
        print("CL1 hypothesis tests (per SAT instance)", flush=True)
        print("=" * 72, flush=True)
        n = cl1s["n_candidates"]
        print(
            f"  Hypothesis (1) — inner SAD on V_1 and V_2 (witness restriction):  "
            f"{100 * cl1s['hypothesis_1_frac']:6.2f}%  "
            f"({cl1s['hypothesis_1_pass']}/{n})",
            flush=True,
        )
        print(
            f"  Hypothesis (2) — both directions bichromatic bridges:           "
            f"{100 * cl1s['hypothesis_2_frac']:6.2f}%  "
            f"({cl1s['hypothesis_2_pass']}/{n})",
            flush=True,
        )
        print(
            f"  Both:                                                          "
            f"{100 * cl1s['both_frac']:6.2f}%  "
            f"({cl1s['both_pass']}/{n})",
            flush=True,
        )

        print("\nBy construction (within SAT instances):", flush=True)
        for k, d in sorted(cl1s["per_construction"].items()):
            print(
                f"  {k:12s} n={d['n']:4d}  "
                f"H1={100*d['h1_frac']:6.2f}%  H2={100*d['h2_frac']:6.2f}%",
                flush=True,
            )

        print("\nConstruction A — by anchor (C_1) shape:", flush=True)
        for k, d in sorted(
            cl1s.get("per_anchor_shape_A", {}).items(),
            key=lambda kv: -kv[1]["n"],
        ):
            print(
                f"  anchor={k:6s} n={d['n']:4d}  "
                f"H1={100*d['h1_frac']:6.2f}%  H2={100*d['h2_frac']:6.2f}%",
                flush=True,
            )

        h1fail = cl1s.get("h1_failure_breakdown", {})
        if h1fail:
            print("\nH1-failure breakdown (V1 status / V2 status):", flush=True)
            for k, v in sorted(h1fail.items(), key=lambda kv: -kv[1]):
                print(f"  {k:40s} count={v}", flush=True)

    if s["verified_unsat"] > 0:
        print("\n" + "=" * 72, flush=True)
        print(
            "WARNING: UNSAT 3-arc-strong OLS candidate(s) found!", flush=True
        )
        print(
            f"   Run team/01 ten-item checklist; canonicalize; "
            f"produce team/12_candidate_counterexample.md.",
            flush=True,
        )
        for ce in log.counterexamples:
            print(f"   - {ce['name']}  n={ce['n']}", flush=True)

    print(f"\nlog: {log_path}", flush=True)
    with log_path.open("w") as f:
        json.dump(asdict(log), f, indent=2, default=str)

    return 0


if __name__ == "__main__":
    sys.exit(main())
