"""GROUND: is C3[QR_19] (order 57, ov=5 EXACT by P23) 5-omega_vec-critical?

Open_crux item (4): level-4 IFF analogue predicts C3[QR_19] is NOT 5-critical
(UNTESTED).  This script tests it.

By VERTEX-TRANSITIVITY (verified here: outer 3-rotation + per-copy inner
translation x->x+1 mod 19 are automorphisms), 5-criticality reduces to ONE
decision: does T - v0 (v0 = vertex 0 = copy0 inner0) admit an order whose
backedge graph has clique <= 4 ?
    YES (clique<=4)  => ov(T-v0)=4 => T IS 5-critical at every vertex (KILL prediction).
    NO  (UNSAT)      => ov(T-v0)=5 => T is NOT 5-critical (CONFIRM prediction).
(Lower bound 4 on T-v0 is free: QR_19 is an induced subtournament, ov(QR_19)=4.)

Phase 'template': cheap explicit orders (restricted gold G59 order, etc.).
Phase 'sat'     : one no-K5 linear-ordering SAT run on the 56-vertex T-v0.
"""
import sys, os, time, signal, functools, json, argparse
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import core
from lexlib import lex_substitute, C3, is_tournament

NI = 19  # inner order

# ---- build QR_19 and C3[QR_19] EXACTLY as decide_ov_c3_qr19.py / G59 ----
QR = sorted({(x * x) % 19 for x in range(1, 19)})
arcs19 = [(i, (i + d) % 19) for i in range(19) for d in QR]
assert core.is_tournament(19, arcs19), "QR_19 not a tournament"
QR19 = (19, arcs19)
N, ARCS = lex_substitute(C3, QR19)
assert is_tournament(N, ARCS)
print("object C3[QR_19] order", N, "QR=", QR, flush=True)

BEATS = core.beats_matrix(N, ARCS)

def vid(copy, inner):
    return copy * NI + inner   # lexlib convention u = o1*ni + a1

# ---- (1) verify vertex-transitivity via two automorphism generators ----
def is_automorphism(perm):
    # perm: list length N, perm[u] = image of u. Check arc-preservation.
    for u in range(N):
        pu = perm[u]
        for v in range(N):
            if u == v:
                continue
            if BEATS[u][v] != BEATS[pu][perm[v]]:
                return False
    return True

# outer rotation: copy c -> c+1 mod 3, inner fixed
outer_rot = [vid((c + 1) % 3, a) for c in range(3) for a in range(NI)]
# inner translation x->x+1 mod 19 applied IN EVERY copy simultaneously
inner_tr = [vid(c, (a + 1) % NI) for c in range(3) for a in range(NI)]

aut_outer = is_automorphism(outer_rot)
aut_inner = is_automorphism(inner_tr)
print("AUT outer 3-rotation:", aut_outer, flush=True)
print("AUT inner +1 (all copies):", aut_inner, flush=True)
# transitivity: orbit of vertex 0 under group generated by these two gens
def orbit(gens, start, N):
    seen = {start}; frontier = [start]
    while frontier:
        x = frontier.pop()
        for g in gens:
            y = g[x]
            if y not in seen:
                seen.add(y); frontier.append(y)
    return seen
orb = orbit([outer_rot, inner_tr], 0, N) if (aut_outer and aut_inner) else {0}
print("orbit of v0 size:", len(orb), "vertex_transitive:", len(orb) == N, flush=True)
VERTEX_TRANSITIVE = (aut_outer and aut_inner and len(orb) == N)

# ---- build T - v0  (delete vertex 0), relabel survivors 0..55 ----
V0 = 0
surv = [u for u in range(N) if u != V0]
relabel = {u: i for i, u in enumerate(surv)}
Nd = len(surv)
arcs_d = []
for (u, v) in ARCS:
    if u == V0 or v == V0:
        continue
    arcs_d.append((relabel[u], relabel[v]))
assert core.is_tournament(Nd, arcs_d), "T-v0 not a tournament"
print("T-v0 order", Nd, "tournament", True, flush=True)

# free lower bound check: ov(QR_19)=4 induced, so ov(T-v0)>=4. We trust ledger.

# ---- candidate explicit orders on T-v0 (in ORIGINAL labels, then relabel) ----
def restrict_order(full_order):
    """drop v0 from a full 57-order, keep relative order, relabel to 0..55."""
    return [relabel[x] for x in full_order if x != V0]

templates = {}

# Template 1: restriction of the G59 gold optimal clique-5 order
gold = json.load(open(os.path.join(os.path.dirname(__file__), "..", "data",
                                   "ground_h21_skeleton_sat.json")))["witness_order"]
assert sorted(gold) == list(range(N))
templates["gold_G59_restricted"] = restrict_order(gold)

# Template 2: inner_then_outer (P19 deletion template flavour): order vertices
# by (inner index, copy) lexicographically.
io = sorted(surv, key=lambda u: (u % NI, u // NI))
templates["inner_then_outer"] = [relabel[u] for u in io]

# Template 3: outer_then_inner
oi = sorted(surv, key=lambda u: (u // NI, u % NI))
templates["outer_then_inner"] = [relabel[u] for u in oi]

# Template 4: d_then_c band order: by inner index, copies interleaved by rotation
dthenc = sorted(surv, key=lambda u: ((u % NI), (u // NI - (u % NI)) % 3))
templates["d_then_c_band"] = [relabel[u] for u in dthenc]


def run_templates():
    best = 99; best_name = None; best_order = None
    for name, order in templates.items():
        assert sorted(order) == list(range(Nd)), name
        w = core.omega_of_order(Nd, arcs_d, order)
        print("  template %-22s backedge clique = %d" % (name, w), flush=True)
        if w < best:
            best = w; best_name = name; best_order = order
    print("BEST template clique =", best, "(", best_name, ")", flush=True)
    if best <= 4:
        # independent re-verify
        w2 = core.omega_of_order(Nd, arcs_d, best_order)
        assert w2 == best
        print("KILL: ov(T-v0)<=4 via template", best_name,
              "=> C3[QR_19] IS 5-critical (re-checked clique=%d)" % w2, flush=True)
        print("VERDICT 5-CRITICAL", flush=True)
        return True, best
    return False, best


def run_sat():
    from pysat.formula import CNF
    from pysat.solvers import Cadical153, Minisat22
    # out-neighbour bitmasks on T-v0
    out = [0] * Nd
    for (u, v) in arcs_d:
        out[u] |= (1 << v)
    # enumerate transitive 5-subsets as source->sink chains
    def enum_chains(K):
        res = []; ap = res.append
        def rec(chosen, cand):
            if len(chosen) == K:
                ap(tuple(chosen)); return
            m = cand
            while m:
                v = (m & -m).bit_length() - 1
                m &= m - 1
                rec(chosen + [v], cand & out[v])
        for s in range(Nd):
            rec([s], out[s])
        return res
    t0 = time.time()
    chains = enum_chains(5)
    print("transitive 5-chains:", len(chains), "(%.2fs)" % (time.time() - t0), flush=True)
    idx = {}; nv = [0]
    def lit(u, v):
        if (u, v) in idx: return idx[(u, v)]
        if (v, u) in idx: return -idx[(v, u)]
        nv[0] += 1; idx[(u, v)] = nv[0]; return nv[0]
    for u in range(Nd):
        for v in range(u + 1, Nd):
            lit(u, v)
    cnf = CNF()
    for u in range(Nd):
        for v in range(Nd):
            if v == u: continue
            for w in range(Nd):
                if w == u or w == v: continue
                cnf.append([-lit(u, v), -lit(v, w), lit(u, w)])
    for ch in chains:
        cnf.append([lit(ch[i], ch[i + 1]) for i in range(4)])
    print("CNF vars", nv[0], "clauses", len(cnf.clauses), flush=True)
    t1 = time.time()
    s = Cadical153(bootstrap_with=cnf.clauses)
    sat = s.solve()
    print("Cadical153 no-K5 SAT =", sat, "(%.2fs)" % (time.time() - t1), flush=True)
    t2 = time.time()
    s2 = Minisat22(bootstrap_with=cnf.clauses)
    sat2 = s2.solve()
    print("Minisat22 no-K5 SAT =", sat2, "(%.2fs)" % (time.time() - t2), flush=True)
    assert sat == sat2, "SOLVER DISAGREEMENT"
    if sat:
        model = set(s.get_model())
        def precedes(u, v):
            l = lit(u, v)
            return (l in model) if l > 0 else ((-l) not in model)
        def cmp(a, b):
            if a == b: return 0
            return -1 if precedes(a, b) else 1
        order = sorted(range(Nd), key=functools.cmp_to_key(cmp))
        w = core.omega_of_order(Nd, arcs_d, order)
        print("INDEPENDENT CHECK backedge clique of SAT witness =", w, flush=True)
        assert w <= 4, "SAT witness clique %d > 4 -- encoding bug" % w
        print("KILL: ov(T-v0)=4 (SAT) => C3[QR_19] IS 5-critical", flush=True)
        print("VERDICT 5-CRITICAL", flush=True)
    else:
        print("CONFIRM: ov(T-v0)=5 (no-K5 UNSAT) => C3[QR_19] is NOT 5-critical", flush=True)
        print("VERDICT NOT-5-CRITICAL", flush=True)
    s.delete(); s2.delete()


def _alarm(sig, frm):
    print("SELF-ALARM TIMEOUT", flush=True); sys.exit(2)
signal.signal(signal.SIGALRM, _alarm)
signal.alarm(560)

if __name__ == "__main__":
    ap = argparse.ArgumentParser()
    ap.add_argument("--phase", choices=["template", "sat", "both"], default="both")
    args = ap.parse_args()
    print("VERTEX_TRANSITIVE =", VERTEX_TRANSITIVE, flush=True)
    assert VERTEX_TRANSITIVE, "vertex-transitivity failed -- single-vertex reduction invalid"
    killed = False
    if args.phase in ("template", "both"):
        killed, best = run_templates()
    if not killed and args.phase in ("sat", "both"):
        run_sat()
    print("DONE", flush=True)
