"""Explicit word-key constructions for the layer volume q0*q1*q2 of B_k.

Angle-1 construction hunt for L_k = min_pi q0 q1 q2 of B_k = C3^k[TT_1].

Every order here is generated by a KEY FUNCTION on the word in {0,1,2}^k
(sort ascending by (key(word), index)).  We verify each claimed layer triple
(q0,q1,q2) by calling the oracle pod_profile on the actual order.

MAIN FINDING (verified, see __main__):
  * Lexicographic order gives EXACTLY (q0,q1,q2)=(1,1,2^k), product 2^k, because
    every backward arc of a coordinate-by-coordinate order lands in one colour.
  * Over ALL generalized-lex orders (any coordinate-reading permutation sigma and
    any per-coordinate digit permutation), the MINIMUM product is exactly 2^k.
    Hence no "simple key read coordinate-by-coordinate" beats 2^k.
  * 2^k matches L_k = 2,4,8 for k=1,2,3 but EXCEEDS L_4 = 15 (16>15).
  * cake(k)=2,4,8,15,26,... equals 2^k only for k<=3; the sub-2^k optima at
    k>=4 are non-product SAT needles not reachable by any key construction here
    (nor by simulated annealing, which gets stuck at the lex value 2^k).
"""
from __future__ import annotations
import itertools
import os
import sys

sys.path.insert(0, os.path.dirname(__file__))
from stilde_pod_profiles import pod_profile, word  # noqa: E402


def order_from_key(depth, keyfn):
    n = 3 ** depth
    o = list(range(n))
    o.sort(key=lambda v: (keyfn(word(v, depth)), v))
    return o


def triple(depth, keyfn):
    p = pod_profile(order_from_key(depth, keyfn), depth)
    h = tuple(p["layer_heights"])
    return h, h[0] * h[1] * h[2]


def cake(k):
    return (k ** 3 + 5 * k + 6) // 6


def min_generalized_lex(depth):
    """Min product over all (coord-perm x per-coord digit-perm) lex orders."""
    n = 3 ** depth
    digperms = list(itertools.permutations(range(3)))
    best = None
    for sigma in itertools.permutations(range(depth)):
        for dperms in itertools.product(digperms, repeat=depth):
            o = list(range(n))
            o.sort(key=lambda v: tuple(dperms[i][word(v, depth)[sigma[i]]]
                                       for i in range(depth)))
            h = pod_profile(o, depth)["layer_heights"]
            p = h[0] * h[1] * h[2]
            if best is None or p < best[0]:
                best = (p, tuple(h))
    return best


if __name__ == "__main__":
    Lk = {1: 2, 2: 4, 3: 8, 4: 15}
    print("k : lex (1,1,2^k)     | min generalized-lex |  L_k   cake(k)")
    for k in range(1, 6):
        lh, lp = triple(k, lambda w: w)  # plain lexicographic
        line = f"{k} : {str(lh):12s}={lp:<4d} |"
        if k <= 4:
            mg = min_generalized_lex(k)
            line += f" {str(mg[1]):12s}={mg[0]:<4d} |"
        else:
            line += "  (skipped, expensive)  |"
        line += f"  L={Lk.get(k)}   cake={cake(k)}"
        print(line)
