#!/usr/bin/env bash
#
# Streaming snark filter for a given order n, using 8 parallel geng `res/mod`
# shards piped directly through the SAT-based nontrivial-snark filter. No
# intermediate cubic_g5_n${n}.g6 file is written: each shard emits only the
# JSONL entries for nontrivial snarks (≈ tens of lines per shard, vs millions
# generated by geng internally).
#
# Resumability: each shard writes to data/catalogues/n${n}_shards/snarks_shard_${i}.jsonl
# and touches data/catalogues/n${n}_shards/shard_${i}.done on success. Re-running
# the script skips shards whose `.done` marker exists. To force a rerun, delete
# the `.done` files.
#
# Usage:
#     scripts/sweep_higher_order.sh 26
#     scripts/sweep_higher_order.sh 26 GENG=/opt/homebrew/bin/geng
#
# Output:
#     data/catalogues/n${n}_shards/snarks_shard_${i}.jsonl  -- per-shard JSONL
#     data/catalogues/n${n}_shards/shard_${i}.done          -- completion marker
#     data/catalogues/n${n}_shards/shard_${i}.log           -- per-shard wall-time log
#     data/catalogues/nontrivial_snarks_n${n}.jsonl         -- merged JSONL (after all shards done)
#     data/catalogues/nontrivial_snarks_n${n}.g6            -- merged g6 (after all shards done)

set -u

N="${1:?usage: $0 <even order n>}"
shift || true

# Optional variable assignments after positional arg (e.g. GENG=/path)
for kv in "$@"; do
    case "$kv" in *=*) export "$kv";; esac
done

GENG="${GENG:-geng}"
VENV_PYTHON="${VENV_PYTHON:-$(pwd)/../../.venv/bin/python}"
SHARDS="${SHARDS:-8}"

DIR="data/catalogues/n${N}_shards"
mkdir -p "$DIR"

# Spawn shards that lack a .done marker
declare -a PIDS
for ((i=0; i<SHARDS; i++)); do
    if [ -f "$DIR/shard_${i}.done" ]; then
        echo "[skip] shard $i/$SHARDS already done ($(wc -l < "$DIR/snarks_shard_${i}.jsonl") snarks)"
        continue
    fi
    (
        t0=$(date +%s)
        "$GENG" -d3 -D3 -c -tf -q "$N" ${i}/${SHARDS} 2>/dev/null \
          | "$VENV_PYTHON" scripts/catalogue.py - --filter nontrivial-snark --emit-jsonl 2>/dev/null \
          > "$DIR/snarks_shard_${i}.jsonl"
        status=$?
        t1=$(date +%s)
        snark_count=$(wc -l < "$DIR/snarks_shard_${i}.jsonl")
        echo "shard=${i}/${SHARDS} status=${status} elapsed_s=$((t1 - t0)) snarks=${snark_count}" \
          > "$DIR/shard_${i}.log"
        if [ "$status" -eq 0 ]; then
            touch "$DIR/shard_${i}.done"
            echo "[done] shard $i/$SHARDS in $((t1 - t0)) s -- $snark_count snarks"
        else
            echo "[fail] shard $i/$SHARDS exit=$status; rerun the script to retry just this shard"
        fi
    ) &
    PIDS+=($!)
done

if [ ${#PIDS[@]} -gt 0 ]; then
    echo "Spawned ${#PIDS[@]} shard worker(s); waiting..."
    wait "${PIDS[@]}"
fi

# Check all done
all_done=true
for ((i=0; i<SHARDS; i++)); do
    if [ ! -f "$DIR/shard_${i}.done" ]; then
        all_done=false
        echo "[warn] shard $i/$SHARDS not done; re-run to retry"
    fi
done

if $all_done; then
    cat "$DIR"/snarks_shard_*.jsonl > "data/catalogues/nontrivial_snarks_n${N}.jsonl"
    "$VENV_PYTHON" -c "
import json, pathlib
out = pathlib.Path('data/catalogues/nontrivial_snarks_n${N}.g6')
with out.open('w') as f:
    for line in pathlib.Path('data/catalogues/nontrivial_snarks_n${N}.jsonl').read_text().splitlines():
        e = json.loads(line)
        f.write(e['graph6'] + '\n')
print(f'wrote {out}: {sum(1 for _ in open(out))} graphs')
"
    total=$(wc -l < "data/catalogues/nontrivial_snarks_n${N}.jsonl")
    echo "[OK] all shards done; merged $total nontrivial snarks at n=$N"
else
    exit 1
fi
